// Auto-generated by sync-contracts.js - DO NOT EDIT
// Last updated: 2025-07-17T08:04:30.730Z

import { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL } from '@/config/chain';

// Re-export for backward compatibility
export { RISE_CHAIN_ID, RISE_RPC_URL, RISE_WS_URL, RISE_EXPLORER_URL };

// Contract addresses for WebSocket subscriptions
export const CONTRACTS = {
  "MockUSDC": "0x3c519dfe8941966adc70a164ef353a43286ed420",
  "SimpleCLOB": "0xd2083ef300d35e8a4b6a1cae9a89a70f64ad3ac7"
} as const;

// Re-export specific contract addresses
export const MOCKUSDC_ADDRESS = '0x3c519dfe8941966adc70a164ef353a43286ed420' as const;
export const SIMPLECLOB_ADDRESS = '0xd2083ef300d35e8a4b6a1cae9a89a70f64ad3ac7' as const;
