[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
skip = ["**/certora/**", "**/test/mocks/**/*.sol", "**/openzeppelin-contracts-upgradeable/certora/**", "**/openzeppelin-contracts/certora/**"]

# RISE Testnet Configuration
[rpc_endpoints]
rise_testnet = "https://testnet.riselabs.xyz/"
localhost = "http://localhost:8545"


